In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data=pd.read_csv("C:/Users/hp/Desktop/New folder (2)/Women Clothing E-Commerce Review.csv")

In [5]:
data.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [7]:
data.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [11]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [12]:
data[data['Review']==""]=np.NaN

In [13]:
data['Review'].fillna(" no review",inplace=True)

In [14]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [15]:
x=data['Review']
y=data['Rating']

In [16]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, train_size=0.8, random_state=2529)

In [26]:
from sklearn.feature_extraction.text import CountVectorizer


cv = CountVectorizer(
    lowercase=True,
    analyzer='word',
    ngram_range=(2, 3),
    stop_words='english',
    max_features=5000
)


In [27]:
X_train=cv.fit_transform(X_train)

In [28]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [29]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
X_test=cv.fit_transform(X_test)

In [32]:
cv.get_feature_names_out()
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
from sklearn.naive_bayes import MultinomialNB


In [35]:
model=MultinomialNB()

In [36]:
model.fit(X_train,y_train)

MultinomialNB()

In [37]:
y_pred =model.predict(X_test)

In [38]:
y_pred.shape

(4698,)

In [39]:
from sklearn.metrics import confusion_matrix, classification_report


In [40]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.07      0.04       174
         2.0       0.06      0.07      0.06       283
         3.0       0.14      0.16      0.15       533
         4.0       0.24      0.22      0.23      1015
         5.0       0.62      0.54      0.58      2693

    accuracy                           0.38      4698
   macro avg       0.22      0.21      0.21      4698
weighted avg       0.43      0.38      0.40      4698



In [41]:
print(confusion_matrix(y_test, y_pred))

[[  13   13   25   29   94]
 [  30   20   51   62  120]
 [  47   61   84  120  221]
 [ 114   72  126  227  476]
 [ 253  186  294  496 1464]]


In [42]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [43]:
data.replace({'Rating':{1:0,2:0,1:0,3:0,4:1,5:1,}},inplace=True)

In [44]:
y=data['Rating']

In [45]:
X_train, X_test, y_train, y_test = train_test_split(x,y, train_size=0.8, random_state=2529)

In [46]:
cv = CountVectorizer(
    lowercase=True,
    analyzer='word',
    ngram_range=(2, 3),
    stop_words='english',
    max_features=5000
)
X_train=cv.fit_transform(X_train)
X_test=cv.fit_transform(X_test)

In [49]:
model2=MultinomialNB()

In [50]:
model.fit(X_train,y_train)

MultinomialNB()

In [51]:
y_pred =model.predict(X_test)

In [52]:
print(confusion_matrix(y_test, y_pred))

[[ 265  725]
 [ 705 3003]]


In [53]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.27      0.27      0.27       990
         1.0       0.81      0.81      0.81      3708

    accuracy                           0.70      4698
   macro avg       0.54      0.54      0.54      4698
weighted avg       0.69      0.70      0.69      4698

